name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v2

    - name: Set up C++ Environment
      uses: actions/setup-cpp@v1
      with:
        compiler: gcc

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Release Repository
      uses: actions/checkout@v2
      with:
        repository: your-username/release-repo
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download Build Artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts

    - name: Copy Build Artifacts
      run: |
        cp -r build/* .

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Deploy new build"
        git push origin master
