name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v2

    - name: Set up C++ Environment
      uses: actions/setup-cpp@v1
      with:
        compiler: gcc

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure
